<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8e01a904fbd54bda5379659e431dc8b7
{
    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Parsedown' => 
            array (
                0 => __DIR__ . '/..' . '/erusev/parsedown',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit8e01a904fbd54bda5379659e431dc8b7::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit8e01a904fbd54bda5379659e431dc8b7::$classMap;

        }, null, ClassLoader::class);
    }
}
